AWSTemplateFormatVersion: 2010-09-09
Description: Code Commit Repository
Parameters: 
  ResourcePrefix:
    Type: String
    Default: user

Resources: 
  MyCodeCommitRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryDescription: My code commit repository
      RepositoryName: !Sub ${ResourcePrefix}-repo

Outputs:
  CodeRepository:
    Value: !Ref MyCodeCommitRepository
  CodeRepositoryArn:
    Value: !GetAtt MyCodeCommitRepository.Arn
